app:
    resource: '@AppBundle/Controller/'
    type: annotation

my-first-route:
   path: this-is-my-first-route
   defaults: {_controller:AppBundle:FirstRoute:showFirstRoute}

populate-borroweditems-test:
   path: setup/pupulate-borroweditems
   defaults: {_controller:AppBundle:Setups:populateBorrowedItems}

read-borroweditems-test:
   path: setup/read-borroweditems
   defaults: {_controller:AppBundle:Setups:readBorrowedItems}

update-borroweditems-test:
   path: setup/update-borroweditems
   defaults: {_controller:AppBundle:Setups:updateBorrowedItems}

delete-borroweditems-test:
   path: setup/delete-borroweditems
   defaults: {_controller:AppBundle:Setups:deleteBorrowedItems}

repository-person-test:
   path: tests/repository-person/{paramname}
   defaults: {_controller:AppBundle:Tests:usePersonRepository}
   requirements:
     paramname: '[a-zA-z]+'

relationships-test:
   path: tests/relationships/{quantity}
   defaults: {_controller: AppBundle:Tests:relationshipTests, quantity:0}
   requirements:
     quantity: '[0-9]+'

relationships-test-procedure:
   path: tests/relationships-procedure/{quantity}
   defaults: {_controller: AppBundle:Tests:relationshipTestsProcedure, quantity:0}
   requirements:
     quantity: '[0-9]+'

relationships-test-procedure-full:
   path: tests/relationships-procedure-full/{quantity}
   defaults: {_controller: AppBundle:Tests:relationshipTestsProcedureFull, quantity:0}
   requirements:
     quantity: '[0-9]+'

procedure-scalar:
   path: tests/procedure-scalar
   defaults: {_controller: AppBundle:Tests:procedureScalar}
