# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    hello:
        class: AppBundle\Service\Hello
        arguments: []

    alwaysTheSame:
        class: AppBundle\Service\AlwaysTheSame
        arguments: []

    uniqueService:
        class: AppBundle\Service\UniqueService
        shared: false
        arguments: []

    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
